import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from 'src/components/SearchBar'
import NavBar from 'src/components/NavBar'

const SearchPage: NextPage = () => {
  return (
    <>
      <Head>
          <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <SearchBar />
      <main>
        <h1>
          hello minsim
        </h1>
        <button 
        
        onClick={() => {
          throw new Error('Sentry Frontend Error')
        }}>
        Throw error
        </button>
        <SearchBar></SearchBar>
      </main>
    </>
  )
}

export default SearchPage
