import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from 'src/components/SearchBar'
import NavBar from 'src/components/NavBar'
import { SloganContainer } from 'styles/SearchStyle'

const SearchPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>검색</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <SearchBar />

      <main>
        <SloganContainer>
          <h1>
            hello minsim
          </h1>
          <button 
          
          onClick={() => {
            throw new Error('Sentry Frontend Error')
          }}>
          Throw error
          </button>
        </SloganContainer>
      </main>
    </>
  )
}

export default SearchPage
