import type { NextPage } from 'next'
import Head from 'next/head'
import DescribeText from 'src/components/DescribeText'
import NavBar from 'src/components/NavBar'
import SimpleWordCloud from 'src/components/WordCloud'
import { TrendSectionStyle } from 'styles/trend/SectionStyle'
import { WordCloudContainer } from 'styles/trend/WordcloudStyle'

const TrendPage: NextPage = () => {
  return (
    <div>
      <Head>
          <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <TrendSectionStyle>
          <DescribeText
              mainText='채널 정보' 
              subText1='채널을 검색해보세요.'
              subText2='다양한 정보가 당신을 기다리고 있습니다.'/>
        </TrendSectionStyle>
        <WordCloudContainer>
          <SimpleWordCloud />
        </WordCloudContainer>
      </main>
    </div>
  )
}

export default TrendPage
