import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from 'src/components/SearchBar'
import { useRouter } from 'next/router'

const ChannelDetailPage: NextPage = () => {
  const router = useRouter()
  const query = router.query
  console.log(query)

  return (
    <div>
      <Head>
          <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          hello minsim
        </h1>
        <button 
        
        onClick={() => {
          throw new Error('Sentry Frontend Error')
        }}>
        Throw error
        </button>
        <SearchBar></SearchBar>
      </main>
    </div>
  )
}

export default ChannelDetailPage
