import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

import DescribeText from 'src/components/DescribeText'
import NavBar from 'src/components/NavBar'
import SimpleWordCloud from 'src/components/TrendList'

import { useQuery } from "react-query";

import { TrendSectionStyle } from 'styles/trend/SectionStyle'
import { WordCloudContainer } from 'styles/trend/WordcloudStyle'
import apitrendList from '../api/apitrendList'
import Tags from 'src/components/Tags'



interface ITrendTag {
  text: string;
  value: number;
}

interface ITrendKeyword {
  text: string;
  value: number;
}

interface Iprops {
  _id: string;
  tags: ITrendTag[];
  keywords: ITrendKeyword[];
}


const TrendPage: NextPage = () => {
  const router = useRouter();
  const query = router.query
  const {
    data: trendList,
    error,
    status,
  } = useQuery<Iprops>(
    ["trendList"],
    () => {
      return apitrendList();
    },
  );
  
  if (status === "loading") {
    return <span>Loading...</span>;
  }

  if (status === "error") {
    return <span>Error </span>;
  }
  

  return (
    <div>
      <Head>
        <title>Trend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <TrendSectionStyle>
          <DescribeText
              mainText='Trend Tag' 
              subText1='태그입니다.'
              subText2='현재 인기동영상의 태그를 확인해 보세요.'/>
        </TrendSectionStyle>
        <WordCloudContainer>
          <SimpleWordCloud props={trendList?.tags}/>
        </WordCloudContainer>
        <TrendSectionStyle>
          <DescribeText
              mainText='Trend Keyword' 
              subText1='키워드입니다.'
              subText2='현재 인기동영상의 키워드를 확인해 보세요.'/>
        </TrendSectionStyle>
        <WordCloudContainer>
          <SimpleWordCloud props={trendList?.keywords}/>
        </WordCloudContainer>
      </main>
    </div>
  )
}

export default TrendPage
