import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from 'src/components/SearchBar'
import NavBar from 'src/components/NavBar'
import { SloganContainer } from 'styles/SearchStyle'
<<<<<<< HEAD:minsim/src/pages/search.tsx
import styled from '@emotion/styled'
import SearchList from 'src/components/SearchList'


const ChannelSearchStyle = styled.div`
   display: flex;
   flex-direction : column;
  `

const SearchPage: NextPage = () => {
=======
import { useRouter } from 'next/router'

const SearchPage: NextPage = () => {
  const router = useRouter()
  console.log(router.query);
>>>>>>> 9103eb37536a7bde37b4118d47a8724aa05f7fef:minsim/src/pages/search/[id]/index.tsx
  
  return (
    <>
      <Head>
        <title>검색</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <NavBar />
      <SearchBar />
      <main>
        <SloganContainer>
          <SearchList />
        </SloganContainer>
      </main>
    </>
  )
}

export default SearchPage
